
markdown: rdiscount
highlighter: pygments
paginate: 8
permalink: /:title
paginate_path: "page:num"

feed: "atom/xml"

title: duandun
url: http://chruyo.com
author_info: <a href="http://weibo.com/duandun">CR</a>
author: duandun
